### ISSUE TITLE
Развертка приложения

### ISSUE THREAD

**Issue by MULTI-FACE** [MULTI-FACE/bizy_flower#4]
Сюда входит создание установочника и тестирование функционала. 
Задание по созданию закрепляется за Кильмякишной Ириной 
Тестирование установочника закрепляется за Бельской Надеждой

**Comment by MULTI-FACE** [comment]
Установочник реализован SetupBF в папке с тем же названием

**Comment by KristinaN98** [comment]
Протестировала на win 7 и win 10 установщик
Полученный результат оформила в отчет и выгрузила в папку doc

**Comment by belskaya** [comment]
Протестировала на win 7 и win 10 установщик
Полученный результат оформила в отчет и выгрузила в папку doc

**Comment by MULTI-FACE** [comment]
На основании отчета было выявлено, что при запуске без прав администратора визуальная часть формы отображается некорректно. Необходимо это указать в руководстве пользователя
